wandb_version: 1

FCC_hidden_layer:
  desc: null
  value: 200
LSTM_hidden_layer:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    viz:
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
batch_size:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 30
optimizer:
  desc: null
  value: adam
